<?php

// hardware_inventory_report.php [OpsHostGuard - Generated by DataManager.ps1]

/**
 * @SYNOPSIS
 * Dynamically generated hardware inventory report page for the OpsHostGuard project.
 * This script loads configurations, checks user login, and displays detailed hardware inventory data
 * with filtering and export options.
 * 
 * @DESCRIPTION
 * - Loads configuration settings from external files to customize page properties, such as the title.
 * - Ensures the user is authenticated; if not, redirects them to the login page.
 * - Provides filtering options to view specific hosts, with export options to generate a PDF report.
 * - This file is generated automatically by the `DataManager.ps1` PowerShell script 
 *   and should not be modified manually.
 * 
 * @NOTES
 * - Requires `config.php` for essential configuration settings, including `BASE_URL`.
 * - Depends on `session_manager.php` for user authentication and session management.
 * - Uses JavaScript libraries (e.g., `html2pdf.js`, `jsPDF`) for client-side PDF export functionality.
 * - Automatically regenerated by the backend as needed; any manual modifications will be overwritten.
 * 
 * @ORGANIZATION
 * Developed for: Faculty of Documentation and Communication Sciences at the University of Extremadura.
 * 
 * @DEPENDENCIES
 * - `config.php`: Loads BASE_URL and other configuration settings.
 * - `session_manager.php`: Manages user authentication and session timeout policies.
 * 
 * @AUTHOR
 * Alberto Ledo [Faculty of Documentation and Communication Sciences] - with assistance from OpenAI
 * IT Department: University of Extremadura - IT Services for Facilities
 * Contact: albertoledo@unex.es
 * 
 * @VERSION
 * 2.0 - Dynamically generated by OpsHostGuard
 * 
 * @LICENSE
 * This script is strictly for internal use within the University of Extremadura.
 * It is designed for the IT infrastructure of the University of Extremadura and may not function 
 * as expected in other environments.
 * 
 * @LINK
 * https://github.com/n7rc/OpsHostGuard
 */

// Load configuration and session management modules
@require_once __DIR__ . '/../../config/config.php';
@require_once __DIR__ . '/../../auth/session_manager.php';

$version = getVersion();
$userData = getUserData();

// Ensure the user is logged in and verify session activity
checkLogin();
checkSessionTimeout();

?>

<!DOCTYPE html>
<html lang='es'>
<head>
    <meta charset='UTF-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <link rel="icon" href="<?php echo BASE_URL; ?>/public/assets/images/favicon.png" type="image/png">
    <title><?php echo $userData['HTMLReport']['hardInventoryReportTitle']; ?></title>

    <!-- External resources for styling and icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>/public/assets/css/main-styles.css">

    <!-- JS Libraries for PDF export functionality -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.4.1/html2canvas.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.9.3/html2pdf.bundle.min.js"></script>
    <script src="<?php echo BASE_URL; ?>/public/assets/js/main.js"></script>
</head>
<body>

<!-- Navigation Bar with links to Dashboard and Logout -->
<div class="navbar">
    <div class="containernav">
        <a href="<?php echo BASE_URL; ?>/views/dashboard/dashboard.php" class="first-link"><i class="fa-solid fa-house"></i></a>
        <a href="<?php echo BASE_URL; ?>/public/index.php" class="last-link"><i class="fa fa-sign-out"></i></a>
    </div>
</div>

<div class="container no-export">
    <!-- Filter Section for Host Selection -->
    <div class="filter-container">
        <form id="filterForm">
            <!-- Dropdown to filter hardware inventory by host -->
            <label for="hostFilter">Filter by Host:</label>
            <select id="hostFilter" name="host">
                <option value='all'>All Hosts</option>
                <?php include('../../../tmp/cache/frontend/html_options_alive_hosts.cache'); ?>
            </select>
        </form>

        <!-- Buttons to apply and reset filters -->
        <button type="button" id="applyFiltersButton" onclick="applyFiltersHardwareInventory()">Apply Filters</button>
        <button type="button" id="resetFiltersButton" onclick="resetFilters()">Reset Filters</button>
    </div>
</div>

<div class="container exportable-content">
    <!-- Header section with title and export button -->
    <div class="header">
        <h1><?php echo $userData['HTMLReport']['hardInventoryReportTitle']; ?></h1>
        <div class="button-group no-export">
            <!--<button class="print-button" onclick="openPrintPreview()">Preview and Print Report</button>-->
            <button class="export-button" onclick="generateInventoryPDF()">Export to PDF (A3)</button>
        </div>
    </div><h2 id='hardware-Inventory'>Hardware Inventory</h2><table id='hardwareInventoryTable'><tr><th>Host</th><th>CPU</th><th>Cores</th><th>RAM (GB)</th>
                         <th>OS Disk (GB)</th><th>Network Adapter</th><th>MAC</th><th>Motherboard</th><th>BIOS Version</th><th>BIOS Release Date</th>
                         <!--<th>OS</th>--><th>OS Build Number</th><th>GPU</th><th>GPU Driver Version</th></tr><tr><td>localhost</td><td>12th Gen Intel(R) Core(TM) i5-12600K</td><td>10</td><td>64</td><td>931</td><td>Realtek Gaming 2.5GbE Family Controller VirtualBox Host-Only Ethernet Adapter</td><td>04:42:1A:EC:D0:96 0A:00:27:00:00:11</td><td>ASUSTeK COMPUTER INC. - PRIME Z690-P WIFI D4</td><td>2404</td><td>03/30/2023 02:00:00</td><td>26100</td><td>Intel(R) UHD Graphics 770</td><td>31.0.101.3959</td></tr><tr><td>n7rcws</td><td>12th Gen Intel(R) Core(TM) i5-12600K</td><td>10</td><td>64</td><td>931</td><td>Realtek Gaming 2.5GbE Family Controller VirtualBox Host-Only Ethernet Adapter</td><td>04:42:1A:EC:D0:96 0A:00:27:00:00:11</td><td>ASUSTeK COMPUTER INC. - PRIME Z690-P WIFI D4</td><td>2404</td><td>03/30/2023 02:00:00</td><td>26100</td><td>Intel(R) UHD Graphics 770</td><td>31.0.101.3959</td></tr></table>
    <p class="version-Info"><?php echo "Version: " . $version; ?> - Date: 2024-11-09 03:12</p></div></body></html>
